# Generated by Django 4.2 on 2024-11-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='responder',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='responder',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='responder',
            name='vehicle_number',
        ),
    ]
